//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Member
    {
        public Member()
        {
            this.Commons = new HashSet<Common>();
        }
    
        public int MID { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public string name { get; set; }
        public string cgpa { get; set; }
    
        public virtual ICollection<Common> Commons { get; set; }
    }
}
